#!/bin/bash
if [[ -z $1 ]]; then
    echo "error: no class provided"
elif hyprctl clients | grep class | awk '{print $2}' | tr '[:upper:]' '[:lower:]' | grep -q $1; then
	switch-to $1
else
	"${@: -1}"
fi
