#!/bin/bash

if [ "$(hyprctl activewindow)" = "Invalid" ]; then
    echo "error: no window is currently focused"
# if no arguments are passed OR current window is the desired program, then move to the next window of this class
elif [[ -z "$1" ]] || [ "$(hyprctl activewindow -j | jq '.class' | tr -d '\"')" = "$1" ]; then
    desired_window_class=$(hyprctl activewindow -j | jq '.class')
    current_window_address=$(hyprctl activewindow -j | jq '.address')
    hyprctl dispatch focuswindow "address:"$(hyprctl clients -j | jq ".[] | select(.class==${desired_window_class}) | .address" | jq -n "[inputs] | .[ (index(${current_window_address})+1) % length]" | tr -d '"')
    hyprctl dispatch alterzorder top
else
    hyprctl dispatch focuswindow $1
    hyprctl dispatch alterzorder top
fi

