# Brightness
bind = ,code:233, exec, brightnessctl s 2.5%+
bind = ,code:232, exec, brightnessctl s 2.5%-

# Volume/Media
binde = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 2%+
binde = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-
bind = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bind = $mainMod CTRL, Down, exec, playerctl play-pause
bind = $mainMod CTRL, Left, exec, playerctl previous
bind = $mainMod CTRL, Right, exec, playerctl next

# Screenshots
#bind = $mainMod CTRL, S, exec, hyprshot --clipboard-only -m region
#bind = ,Print, exec, hyprshot --clipboard-only -m screen
#bind = $mainMod CTRL SHIFT, S, exec, sleep 3 && hyprshot --clipboard-only -m region
#bind = SHIFT, Print, exec, sleep 3 && hyprshot --clipboard-only -m screen
#bind = $mainMod Print, exec, hyprshot  -m region


# Screenshots
bind = $mainMod CTRL, S, exec, grimblast --freeze copy area
bind = ,Print, exec, grimblast --freeze copy screen
bind = $mainMod CTRL SHIFT, S, exec, sleep 3 && grimblast --freeze copy area
bind = SHIFT, Print, exec, sleep 4 && grimblast -freeze copy screen

# Hypr
bind = $mainMod SHIFT, R, exec, hyprpicker -a
bind = $mainMod SHIFT, L, exec, sh ~/.config/hypr/scripts/toggle_autosuspend.sh

# Wellbeing
bind = $mainMod, P, exec, sh ~/.config/hypr/scripts/posture_check_launcher.sh
bind = $mainMod, O, exec, sh ~/.config/hypr/scripts/pomodoro_launcher.sh
bind = $mainMod SHIFT, T, exec, sh ~/.config/hypr/scripts/toggle_eww_tasks.sh

# Gaps
bind = $mainMod CTRL, G, exec, hyprctl --batch "dispatch exec sh ~/.config/waybar/launch.sh small; keyword general:border_size 8; keyword general:gaps_in 0; keyword general:gaps_out 0,0,0,0; keyword decoration:rounding 0; keyword plugin:hy3:tabs:padding 0; keyword plugin:hy3:tabs:rounding 0; keyword general:col.inactive_border rgb(1d212a); keyword general:col.active_border rgb(5a79aa); keyword plugin:hy3:tabs:col.active rgb(5a79aa)"
bind = $mainMod, G, exec, hyprctl --batch "dispatch exec sh ~/.config/waybar/launch.sh; keyword general:border_size 4; keyword general:gaps_in 5; keyword general:gaps_out 1,5,5,5; keyword decoration:rounding 5; keyword plugin:hy3:tabs:padding 5; keyword plugin:hy3:tabs:rounding 5; keyword general:col.inactive_border rgba(595966aa); keyword general:col.active_border rgba(5a81c9ee); keyword plugin:hy3:tabs:col.active rgb(5a81c9)"
bind = $mainMod SHIFT, G, exec, hyprctl --batch "keyword general:gaps_in 5; keyword general:gaps_out 80"

